tirian_trains/tickets/urls.py
from django.urls import path
from .views import (
            homepage_view, passenger_login_view, passenger_create_view, passenger_sign_in_view,
            book_ticket_interface_view, confirm_booking_view, confirm_remove_view
        )

urlpatterns = [
        path("", homepage_view, name="homepage"),
        path("login", passenger_login_view, name="passenger-login"),    
        path("create-user", passenger_create_view, name="passenger-create"),
        path("sign-in", passenger_sign_in_view, name="passenger-sign-in"),
        path("book-ticket", book_ticket_interface_view, name="book-ticket"),
        path("confirm-booking", confirm_booking_view, name="confirm-booking"),
        path("confirm-remove", confirm_remove_view, name="confirm-remove")
]

app_name = "tickets"

tirian_trains/tirian_trains/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('tickets/', include("tickets.urls")),
    path('', include("tickets.urls")),
    path('scheduled_trips/', include("scheduled_trips.urls")),
    path('trains/', include("trains.urls"))
]

tirian_trains/trains/urls.py
from django.urls import path


urlpatterns = [
]

tirian_trains/tickets/models.py
import datetime
from django.db import models
from django.urls import reverse

class Passenger(models.Model):
    customer_id = models.IntegerField(primary_key=True, default=0000)
    last_name = models.CharField(max_length=100, default="Doe")
    given_name = models.CharField(max_length=100, default="John")
    middle_initial = models.CharField(max_length=2, blank=True)
    birth_date = models.DateField(default=datetime.date.today)
    gender = models.CharField(max_length=100, blank=True)

    def get_age(self):
        return int((datetime.date.today().year - self.birth_date.date().year) / 365.25)

    def __str__(self):
       return f"{self.customer_id} - {self.last_name}, {self.given_name} {self.middle_initial}" 

    def get_absolute_url(self):
        return reverse('tickets:passenger-details')


class Ticket(models.Model):
    ticket_id = models.IntegerField(primary_key=True, default=00000)
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    trip = models.ForeignKey("scheduled_trips.Trip", on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return f"Ticket {self.ticket_id}: {self.trip.route.start_station} - {self.trip.route.end_station}" 

    def get_absolute_url(self):
        return reverse('tickets:passenger-details', kwargs={'pk':self.pk})

tirian_trains/tickets/forms.py
import datetime

from django import forms
from .models import Passenger
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    customer_id = forms.IntegerField(label='User ID')
    
    def clean_customer_id(self):
        customer_id = self.cleaned_data["customer_id"]
        if customer_id not in list(Passenger.objects.values_list('customer_id', flat=True)):
            raise ValidationError(
                "User does not exist."
            )
        return customer_id


class PassengerForm(forms.ModelForm):
    class Meta:
        model = Passenger
        fields = ['last_name', 'given_name', 'middle_initial', 'birth_date', 'gender']
        widgets = {
            'birth_date': forms.DateInput(attrs=dict(type='date'))
        }


    def clean_birth_date(self):
        birth_date = self.cleaned_data["birth_date"]
        if birth_date:
            if birth_date > datetime.date.today():
                raise ValidationError(
                    "Not yet born."
                )
        return birth_date

tirian_trains/tickets/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import LoginForm, PassengerForm
from .models import Passenger, Ticket
from scheduled_trips.models import Trip

def homepage_view(request):
    return render(request, 'tickets/homepage.html')

def passenger_sign_in_view(request):
    return render(request, 'tickets/passenger-sign-in.html')

def book_ticket_interface_view(request):
    if request.method == 'POST':
        customer_id=request.POST.get("customer_id")
        trip_id=request.POST.get("trip_id")
        request.session['customer_id'] = customer_id
        request.session['trip_id'] = trip_id
        if request.POST.get("remove"):
            ticket_id=request.POST.get("ticket_id")
            request.session['ticket_id'] = ticket_id
            return redirect('tickets:confirm-remove')
        return redirect('tickets:confirm-booking')
    customer_id=request.session.get("customer_id")
    currentTickets = list(Ticket.objects.raw("""
                                        SELECT ticket_id 
                                        FROM tickets_ticket 
                                        WHERE passenger_id = %s""",[customer_id]))
    totalCost = 0
    for ticket in currentTickets: 
        totalCost+=ticket.trip.route.price
    context = {'user':Passenger.objects.get(pk=customer_id),
               'Trips':Trip.objects.all(),
               'currentTickets':currentTickets,
               'totalCost':totalCost
               }
    return render(request, 'tickets/book-ticket-interface.html', context)

def confirm_booking_view(request):
    if request.method == 'POST':
        customer_id=request.POST.get("customer_id")
        trip_id=request.POST.get("trip_id")
        customer = Passenger.objects.get(pk=customer_id)
        trip = Trip.objects.get(pk=trip_id)

        used_tickets=list(Ticket.objects.values_list('ticket_id', flat=True))
        i=1
        while(True):
            if i in used_tickets:
                i+=1
            else:
                ticket_id=i
                break

        t = Ticket(ticket_id=ticket_id, passenger=customer, trip=trip)
        t.save()
        context = {'ticket':t}
        return render(request, 'tickets/thank-you.html', context)
    context = {'user':Passenger.objects.get(pk=request.session.get("customer_id")),
               'trip':Trip.objects.get(pk=request.session.get("trip_id"))
            }
    return render(request, 'tickets/confirm-booking.html', context)

def confirm_remove_view(request):
    if request.method == 'POST':
        customer_id = request.POST.get("customer_id")
        request.session['customer_id'] = customer_id
        ticket_id=request.POST.get("ticket_id")
        t = Ticket.objects.filter(pk=ticket_id)
        t.delete()
        return redirect('tickets:book-ticket')
    context = {'user':Passenger.objects.get(pk=request.session.get("customer_id")),
               'trip':Trip.objects.get(pk=request.session.get("trip_id")),
               'ticket':Ticket.objects.get(pk=request.session.get("ticket_id"))
            }
    return render(request, 'tickets/confirm-remove.html', context)

def passenger_login_view(request):
    if request.method == 'POST':
        if request.POST.get("customer_id"):
            request.session['customer_id'] = request.POST.get("customer_id")
            return redirect('tickets:book-ticket')
        form=LoginForm(request.POST)
        if form.is_valid():
            customer_id=form.cleaned_data["customer_id"]
            request.session['customer_id'] = customer_id
            return redirect('tickets:book-ticket') 
        else:
            return render(request, 'tickets/passenger-login.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'tickets/passenger-login.html', {'form': form})
    

def passenger_create_view(request):
    if request.method == 'POST':
        form = PassengerForm(request.POST)
        if form.is_valid():
            last_name = form.cleaned_data["last_name"]
            given_name = form.cleaned_data["given_name"]
            middle_initial = form.cleaned_data["middle_initial"]
            birth_date = form.cleaned_data["birth_date"]
            gender = form.cleaned_data["gender"]

            used_ids=list(Passenger.objects.values_list('customer_id', flat=True))
            i=1
            while(True):
                if i in used_ids:
                    i+=1
                else:
                    customer_id=i
                    break

            p = Passenger(
                    customer_id=customer_id, 
                    last_name=last_name, 
                    given_name=given_name,
                    middle_initial=middle_initial,
                    birth_date=birth_date,
                    gender=gender
                )
            p.save()
            
            request.session["customer_id"]=customer_id
            return redirect('tickets:book-ticket')
        else:
            return render(request, 'tickets/passenger-create.html',{'form': form})
    else:    
        form = PassengerForm()

    return render(request, 'tickets/passenger-create.html',{'form': form})

tirian_trains/tickets/templates/tickets/book-ticket-interface.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Tirian Trains {% endblock %}
{% block content %}
<header>
  <nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
    <div class="container-fluid">
        <div class="navbar-header mx-3">
            <a href="{% url 'tickets:homepage' %}">
                <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
            </a>
        </div>
  </nav>
</header>

<div class="container-fluid p-5 has-bg-img"
  style="color: #e6efe4; background-image: url('static/home-bg.png'); background-repeat:repeat-y; background-size: cover; width: 100%;">
  <h1 style="color: #e6efe4; text-align: center; font-family: 'Noto Serif', serif;">Book a Ticket</h1>
  <br>
  <h3 style="font-family: 'Noto Serif', serif;">Logged in as User {{ user.customer_id }}: {{ user.given_name }} {{ user.middle_initial }} {{user.last_name }}</h3>
  <br>
  <h2 style="font-family: 'Noto Serif', serif;">Your Current Trips:</h2>
  <div style="padding:15px;" class="border-white p-3 bg-info bg-opacity-10 border border-info rounded-3">
  <h3>Total Cost: <b>{{ totalCost }} </b>Lion Coins</h3>
  <br>
  <table class="table" style="color: #e6efe4;">
  <tr>
    <th scope="col">Trip #</th>
    <th scope="col">Origin</th>
    <th scope="col">Destination</th>
    <th scope="col">Departure</th>
    <th scope="col">Arrival</th>
    <th scope="col">Duration</th>
    <th scope="col">Cost</th>
    <th scope="col">Cancel</th>
  </tr>
  {% for ticket in currentTickets %}
    <tr>
      <td>{{ ticket.trip.trip_id }}</td>
      <td>{{ ticket.trip.route.start_station.name }}</td>
      <td>{{ ticket.trip.route.end_station.name }}</td>
      <!-- ticket.trip.departure|date:"M d, Y H:i" -->
      <td>{{ ticket.trip.departure|date:"M d, Y H:i" }}</td>
      <td>{{ ticket.trip.arrival|date:"M d, Y H:i" }}</td>
      <td>{{ ticket.trip.get_duration }}</td>
      <td>{{ ticket.trip.route.price }} Lion Coins</td>
      <td>
      <form action="/book-ticket" method='POST'>
        {% csrf_token %}
        <input type="hidden" id="remove" name="remove" value="remove">
        <input type="hidden" id="customer_id" name="customer_id" value={{ user.customer_id }}>
        <input type="hidden" id="trip_id" name="trip_id" value={{ ticket.trip.trip_id }}>
        <input type="hidden" id="ticket_id" name="ticket_id" value={{ ticket.ticket_id }}>
        <input class="btn btn-sm" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;" value="Cancel Trip">
        <br><br>
      </form>
      </td>
    </tr>  
  {% endfor %}
  </table>
  </div>
  <br>
  <h2 style="font-family: 'Noto Serif', serif;">Available Trips</h2>
  <div style="padding:15px;" class="border-white p-3 bg-info bg-opacity-10 border border-info rounded-3">
  <table class="table" style="color: #e6efe4;">
    <tr>
      <th scope="col">Trip #</th>
      <th scope="col">Origin</th>
      <th scope="col">Destination</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
      <th scope="col">Duration</th>
      <th scope="col">Cost</th>
      <th scope="col">Book Ticket</th>
    </tr> 
  {% for trip in Trips %}
    <tr>
      <td>{{ trip.trip_id }}</td>
      <td>{{ trip.route.start_station.name }}</td>
      <td>{{ trip.route.end_station.name }}</td>
      <td>{{ trip.departure|date:"M d, Y H:i" }}</td>
      <td>{{ trip.arrival|date:"M d, Y H:i" }}</td>
      <td>{{ trip.get_duration }}</td>
      <td>{{ trip.route.price }} Lion Coins</td>
      <td>
        <form action="/book-ticket" method='POST'>
          {% csrf_token %} 
          <input type="hidden" id="customer_id" name="customer_id" value={{ user.customer_id }}>
          <input type="hidden" id="trip_id" name="trip_id" value={{ trip.trip_id }}>
          <input class="btn btn-sm text-center" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;" value="Book">
          <br><br>
        </form>
      </td>    
    </tr>
  {% endfor %}
  </table>
  </div>

  <div class="container-fluid footer" style="background:#000301; width: 100%;">
    <footer class="py-2">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted">Book</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        </ul>
        <p class="text-center text-muted">© 2022 Tirian Trains, Inc</p>
    </footer>
  </div>

  {% endblock %}
</div>

tirian_trains/tickets/templates/tickets/confirm-booking.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Confirmation Screen {% endblock %}
{% block content %}
<nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
    <div class="container-fluid">
        <div class="navbar-header mx-3">
            <a href="{% url 'tickets:homepage' %}">
                <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
            </a>
        </div>
</nav>

<div class="container-fluid p-5 has-bg-img"
    style="background-image: url('static/confirm-bg.jpg'); background-size: cover; width: 100%; height:100vh;">
    <div>
    <h2 style="color: #e6efe4; text-align: center; font-family: 'Noto Serif', serif;">Please ensure all the trip details are correct</h2>

    <div class="container-fluid mt-2 p-4 pb-2 rounded" style="width: 800px; background-color: #660000;">
        <div class="text-center">
          <div class="container-fluid">
            <img src="{% static 'tirian-logo.png' %}" width="50" height="50">
          </div>
            <h5 class="pb-1" style="font-family: 'Open Sans', sans-serif; color: #e6efe4;"><br>
                <p>
                  Passenger #{{ user.customer_id }}: {{ user.given_name }} {{ user.middle_initial }} {{user.last_name }}
                </p>
               <p>
                  From {{ trip.route.start_station.name }}<br>
                  To {{ trip.route.end_station.name }}<br>
                  <br>
                  {{ trip.departure|date:"M d, Y H:i" }} - {{ trip.arrival|date:"M d, Y H:i" }} ({{ trip.get_duration }})<br>
                </p>
                <p>
                  {{ trip.route.price }} Lion Coins
                </p>
            </h5>
        </div>
    </div>

    <div class="text-center p-3">
        <form action="/confirm-booking" method='POST'>
            <b><button class="btn btn-lg" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;">Confirm</button></b>
            {% csrf_token %}
            <input type="hidden" id="customer_id" name="customer_id" value={{ user.customer_id }}>
            <input type="hidden" id="trip_id" name="trip_id" value={{ trip.trip_id }}>
        </form>
        <br>
        <form action="/book-ticket" method='submit'>
            <b><button class="btn btn-sm" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;">Return to Bookings</button></b>
        </form>
    </div>
    </div>
</div>
<div class="container-fluid" style="background:#000301; width: 100%">
    <footer class="py-1">
        <ul class="nav justify-content-center border-bottom py-3">
        <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Home</a></li>
        <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Book</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Pricing</a></li>
        </ul>
        <p class="text-center text-muted py-3">© 2022 Tirian Trains, Inc</p>
    </footer>
</div>
{% endblock %}

tirian_trains/tickets/templates/tickets/confirm-remove.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Confirmation Screen {% endblock %}
{% block content %}

<nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
    <div class="container-fluid">
        <div class="navbar-header mx-3">
            <a href="{% url 'tickets:homepage' %}">
                <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
            </a>
        </div>
</nav>

<div class="container-fluid p-5 has-bg-img"
    style="background-image: url('static/confirm-bg.jpg'); background-size: cover; width: 100%; height:100vh;">
    <div>
    <h2 style="color: #e6efe4; text-align: center; font-family: 'Noto Serif', serif;">Cancel the following trip?</h2>

    <div class="container-fluid mt-2 p-4 pb-2 rounded" style="width: 800px; background-color: #660000;">
        <div class="text-center">
          <div class="container-fluid">
            <img src="{% static 'tirian-logo.png' %}" width="50" height="50">
          </div>
            <h5 class="pb-1" style="font-family: 'Open Sans', sans-serif; color: #e6efe4;"><br>
                <p>
                  Passenger #{{ user.customer_id }}: {{ user.given_name }} {{ user.middle_initial }} {{user.last_name }}
                </p>
               <p>
                  From {{ trip.route.start_station.name }}<br>
                  To {{ trip.route.end_station.name }}<br>
                  <br>
                  {{ trip.departure|date:"M d, Y H:i" }} - {{ trip.arrival|date:"M d, Y H:i" }} ({{ trip.get_duration }})<br>
                </p>
                <p>
                  {{ trip.route.price }} Lion Coins
                </p>
            </h5>
        </div>
    </div>

    <div class="text-center p-3">
        <form action="/confirm-remove" method='POST'>
            <b><button class="btn btn-lg" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;">Confirm</button></b>
            {% csrf_token %}
            <input type="hidden" id="customer_id" name="customer_id" value={{ user.customer_id }}>
            <input type="hidden" id="ticket_id" name="ticket_id" value={{ ticket.ticket_id }}>
          </form>
        <br>
        <form action="/book-ticket" method='submit'>
            <b><button class="btn btn-sm" type="submit" style="border-color: #660000; color: #e6efe4; background-color: #270013; font-family: 'Open Sans', sans-serif;">Return to Bookings</button></b>
        </form>
    </div>
    </div>
</div>
<div class="container-fluid" style="background:#000301; width: 100%">
    <footer class="py-1">
        <ul class="nav justify-content-center border-bottom py-3">
        <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Home</a></li>
        <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Book</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Pricing</a></li>
        </ul>
        <p class="text-center text-muted py-3">© 2022 Tirian Trains, Inc</p>
    </footer>
</div>
{% endblock %}

tirian_trains/tickets/templates/tickets/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Tirian Trains {% endblock %}
{% block content %}
<nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
    <div class="container-fluid">
        <div class="navbar-header mx-3">
            <a href="{% url 'tickets:homepage' %}">
                <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
            </a>
        </div>
</nav>

<div class="container-fluid p-5 has-bg-img"
    style="background-image: url('static/home-bg.png'); background-size: cover; width: 100%; height:100vh;">
    <div>
        <img class="img-responsive mx-auto d-block p-3" src="{% static 'tirian-logo-text.png' %}" width="700">
    <h2 style="color: #e6efe4; text-align: center; font-family: 'Noto Serif', serif;">Your tier-one travel companion.</h2>
    
    <div class="text-center p-3">
        <form action="{% url 'tickets:passenger-sign-in' %}">
            <b><button class="btn btn-outline-danger btn-lg" type="submit" style="border-color: #660000; color: #e6efe4; font-family: 'Open Sans', sans-serif;">Book Ticket</button></b>
        </form>
    </div>
    </div>
</div>

<div class="container-fluid" style="background:#000301; width: 100%;">
    <footer class="py-1">
        <ul class="nav justify-content-center border-bottom py-3">
        <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Home</a></li>
        <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Book</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Pricing</a></li>
        </ul>
        <p class="text-center text-muted py-3">© 2023 Tirian Trains, Inc</p>
    </footer>
</div>
 
{% endblock %}

tirian_trains/tickets/templates/tickets/passenger-create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create User {% endblock %}
{% block content %}
<nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
  <div class="container-fluid">
      <div class="navbar-header mx-3">
          <a href="{% url 'tickets:homepage' %}">
              <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
          </a>
      </div>
</nav>

<div class="container-fluid mt-2 p-4 pr-5 rounded" style="width: 250px; background-color: #660000; font-family: 'Open Sans', sans-serif; color: #e6efe4;">
  <div class="text-center">
      <h4 class="pb-1" style="font-family: 'Open Sans', sans-serif; color: #e6efe4;">Create a user account.</h4>
      <div class="text-right" style="text-align: right; color:black;">
        {{ form.non_field_errors }}
        {% for field in form %}
          {% if field.errors %}
            <p>{{ field.label }} has the following errors:</p>
            <ul>
            {% for error in field.errors %}
              <li>{{ error }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endfor %}
      </div>
    </div>
      <form action="/create-user" method="post">
        {% csrf_token %}
        {{ form }}
        <br><br><b><button class="btn" type="submit" style="background-color: #e2d6b2; color: #000301; font-family: 'Open Sans', sans-serif;">Sign Up</button></b>
      </form>
  </div>
</div>

<div class="container-fluid" style="background:#000301; width: 100;">
  <footer class="py-1 fixed-bottom">
      <ul class="nav justify-content-center border-bottom py-3">
      <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Home</a></li>
      <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Book</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Pricing</a></li>
      </ul>
      <p class="text-center text-muted py-3">© 2023 Tirian Trains, Inc</p>
  </footer>
</div>

{% endblock %}

tirian_trains/tickets/templates/tickets/passenger-sign-in.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Tirian Trains Login {% endblock %}
{% block content %}
<nav class="navbar p-3 px-4" style="background: #000301; width:100%; display: flex;">
    <div class="container-fluid">
        <div class="navbar-header mx-3">
            <a href="{% url 'tickets:homepage' %}">
                <img class="img-responsive" src="{% static 'tirian-logo.png' %}" width="50" height="50">
            </a>
        </div>
</nav>


<div class="container-fluid mt-2 p-4 pb-2 rounded" style="width: 400px; background-color: #660000;">
    <div class="text-center">
        <h4 class="pb-1" style="font-family: 'Open Sans', sans-serif; color: #e6efe4;">To continue booking, create or log into an account.</h4>
        <form class="m-3" action="{% url 'tickets:passenger-create' %}">
            <b><button class="btn" type="submit" style="background-color: #e2d6b2; color: #000301; font-family: 'Open Sans', sans-serif;">Sign Up</button></b>
        </form>
        <form class="m-3" action="{% url 'tickets:passenger-login' %}">
            <b><button class="btn" type="submit" style="background-color: #e2d6b2; color: #000301; font-family: 'Open Sans', sans-serif;">Sign In</button></b>
        </form>
    </div>
</div>

    <footer class="py-1 fixed-bottom">
        <ul class="nav justify-content-center border-bottom py-3">
        <li class="nav-item"><a href="{% url 'tickets:homepage' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Home</a></li>
        <li class="nav-item"><a href="{% url 'tickets:passenger-sign-in' %}" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Book</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted" style="color: #e6efe4; text-align: center; font-family: 'Open Sans', sans-serif;">Pricing</a></li>
        </ul>
        <p class="text-center text-muted py-3">© 2023 Tirian Trains, Inc</p>
    </footer>

 
{% endblock %}